{
 "title": "Kamon System  - JVM metrics Copy",
 "description": "Node jvm metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(jvm_memory_buffer_pool_count, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Class loaded - unloaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_class_loading_loaded", "legendFormat": "loaded - {{instance}}" },
    { "expr": "jvm_class_loading_unloaded", "legendFormat": "unloaded - {{instance}}" }
   ]
  },
  {
   "title": "Number of threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "heap size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{region=\"heap\"}"
    },
    {
     "expr": "jvm_memory_committed_bytes{region=\"heap\"}",
     "legendFormat": "committed {{instance}} - {{region}}"
    },
    {
     "expr": "rate(jvm_memory_used_bytes_sum{region=\"heap\"}[5m])/rate(jvm_memory_used_bytes_count{region=\"heap\"}[5m])",
     "legendFormat": "used  {{instance}} - {{region}}"
    }
   ]
  },
  {
   "title": "non-heap memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_memory_used_bytes_sum{ region=\"non-heap\"}[5m])/rate(jvm_memory_used_bytes_count{ region=\"non-heap\"}[5m]))",
     "legendFormat": "used bytes non heap"
    },
    {}
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum{ instance=~\"$node\"}[2m])/rate(jvm_gc_seconds_count{ instance =~\"$node\"}[2m])",
     "legendFormat": " {{instance}}  GC count: {{collector}}"
    }
   ]
  }
 ]
}