#!/bin/bash

docker-compose up -d

echo 'creating resources...'

#######
# unconment if you need to check some docker app status is up
#while true
#do
#    sleep 10
#    echo 'checking status.....'
#    INITIALIZED=$(docker-compose logs precondition_app | grep 'initialization completed' | wc -l)
#    if [[ $INITIALIZED -gt 0 ]]; then
#        echo 'precondition complete initialize'
#        break
#    fi
#done

echo 'finished creating resources'
